# Generated by Django 5.0.2 on 2024-03-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='person.png', upload_to='profile_pics'),
        ),
    ]
