# Generated by Django 5.0.2 on 2024-02-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0006_task_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='i_complete',
            field=models.BooleanField(default=False),
        ),
    ]
