# Generated by Django 5.0.2 on 2024-02-25 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0007_remove_task_completed_task_i_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='i_complete',
            new_name='is_complete',
        ),
    ]
