# Generated by Django 5.0.2 on 2024-02-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0008_rename_i_complete_task_is_complete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_complete']},
        ),
    ]
