# Generated by Django 5.0.2 on 2024-02-26 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0009_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-is_complete']},
        ),
    ]
