# Generated by Django 5.0.2 on 2024-02-26 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0011_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created_at', 'is_complete']},
        ),
    ]
