# Generated by Django 5.0.2 on 2024-02-29 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0016_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_complete', '-created_at']},
        ),
    ]
